on:
  push:
    tags:
      - v*
    branches:
      - master
    paths:
      - "**.go"
      - "Makefile"
      - "**.yaml"
      - "**.yml"
      - "test/**"
  pull_request:
    paths:
      - "**.go"
      - "Makefile"
      - "**.yaml"
      - "**.yml"
      - "test/**"
name: Operator E2E Test
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          go-version: 1.20.x
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/cache@8492260343ad570701412c2f464a5877dc76bace # v2
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
            .bin
          key: cache-${{ hashFiles('**/go.sum') }}-${{ hashFiles('.bin/*') }}
          restore-keys: |
            cache-
      - run: make bin
      - name: Test
        run: ./test/e2e-operator.sh
